import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext"
import { ProjectProvider } from "@/context/ProjectContext"
import { ActivityProvider } from "@/context/ActivityContext"
import CommandPalette from "@/components/layout/CommandPalette"
import Sidebar from "@/components/layout/Sidebar"
import Navbar from "@/components/layout/Navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <ThemeProvider>
          <ProjectProvider>
            <ActivityProvider>
              <CommandPalette />
              <div className="flex h-screen overflow-hidden w-full">
                <Sidebar />
                <div className="flex-1 flex flex-col min-w-0 overflow-y-auto">
                  <Navbar />
                  <main className="flex-1 flex flex-col relative w-full">
                    {children}
                  </main>
                </div>
              </div>
            </ActivityProvider>
          </ProjectProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
